version: 2
updates:
  # ===== Pacchetti npm =====
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]
    ignore:
      - dependency-name: eslint
        update-types: ['version-update:semver-major']
      - dependency-name: '@eslint/js'
        update-types: ['version-update:semver-major']

  # ===== GitHub Actions =====
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns: ['*']
