// ===== Testi in inglese =====
import {
  buildContactLinks,
  buildNavItems,
  buildScreenshots,
  certifications,
  sharedProfile,
} from './shared'

export const en = {
  meta: {
    title: 'Lorenzo Caputo | Junior Developer in Training',
    description: 'Portfolio of Lorenzo Caputo, a junior developer in training at ITS Academy Apulia Digital Maker: project, background and skills.',
    ogTitle: 'Lorenzo Caputo | Junior Developer in Training',
    ogDescription: 'Junior developer in training: background, skills and the My Tracking App project.',
    twitterTitle: 'Lorenzo Caputo | Junior Developer in Training',
    twitterDescription: 'Junior developer in training: background, skills and the My Tracking App project.',
    ogLocale: 'en_US',
    image: '/social-preview-en.jpg',
    imageAlt: 'Lorenzo Caputo portfolio preview',
  },
  ui: {
    skipToContentLabel: 'Skip to content',
    backToTopAria: 'Back to top',
    primaryNavAria: 'Primary',
    mobileNavAria: 'Mobile',
    menuToggleAria: 'Toggle navigation menu',
    openGitHubAria: 'GitHub profile',
    languageSwitcherAria: 'Language selector',
  },
  profile: {
    ...sharedProfile,
    role: 'Junior developer in training',
    school: 'ITS Academy Apulia Digital Maker',
    location: 'Lecce, Puglia, Italy',
    portraitAlt: 'Portrait of Lorenzo Caputo',
    headlineLead: 'I build software with',
    headlineAccent: 'care',
    headlineTrail: 'and method, one step at a time',
    intro: "I'm Lorenzo, a junior developer in training at ITS Academy Apulia Digital Maker. I took My Tracking App, an Android app built with Flutter, all the way to release and keep improving it.",
    introNote: 'I work across frontend, Java backend and hardware: I like understanding how a project works end to end.',
    ctaProject: 'See the project',
    ctaCv: 'Download CV',
  },
  navItems: buildNavItems(['About', 'Background', 'Skills', 'Project', 'Contact']),
  about: {
    eyebrow: 'About',
    title: 'From working with people to building software',
    lead: 'I come from years of customer-facing work and a long-standing passion for hardware: today I bring both into my path as a developer.',
    paragraphs: [
      'At ITS Academy I study Java, OOP, SQL databases, Git and cloud architectures. Front-of-house and front-office work taught me to handle pressure, communicate clearly and work as a team.',
      'I bring both into my projects: tidy code and attention to the people who will use it.',
    ],
    principlesEyebrow: 'How I work',
    principles: [
      {
        title: 'Follow-through',
        text: 'I finish what I start, details included, and leave the work tidy for whoever comes next.',
      },
      {
        title: 'Clear choices',
        text: 'I prefer solutions that are easy to read and maintain over quick shortcuts.',
      },
      {
        title: 'The whole picture',
        text: 'Before touching the code, I try to understand how the pieces fit together.',
      },
    ],
  },
  journey: {
    eyebrow: 'Background',
    title: 'Education and experience',
    educationLabel: 'Education',
    experienceLabel: 'Experience',
    certificationsLabel: 'Certifications',
    education: [
      {
        period: 'Jan 2026 – present',
        title: 'ITS Academy Apulia Digital Maker',
        place: 'Higher Technician in Software Development (EQF 5)',
        text: '1,800 hours on Java and C# (OOP), SQL databases, Git/GitHub, cloud architectures and AI integration, with hands-on coding and debugging labs.',
      },
      {
        period: '2022',
        title: 'Scientific-Linguistic High School Diploma',
        place: 'I.I.S.S. "G.C. Vanini" – Casarano',
        text: 'Logic, mathematics, physics and foreign languages; Cambridge English B2 First certification.',
      },
    ],
    experience: [
      {
        period: '2014 – present',
        title: 'Technical Support & Hardware',
        place: 'Freelance',
        text: 'Diagnosis and repair of PCs and mobile devices, custom workstation builds, local network setup and operating system tuning.',
      },
      {
        period: 'Jun – Sep 2025',
        title: 'Hospitality & Team Coordination',
        place: 'Pizzeria Trattoria "Nicolò"',
        text: 'Managing a section at peak times, digital orders on handheld devices and coordination between floor and kitchen.',
      },
      {
        period: 'Jul 2017 – Sep 2019',
        title: 'Front-of-House & Front-Office',
        place: 'Ristorante Pizzeria "Il Gambero Rosso"',
        text: 'Welcoming international guests, handling payments and the front desk, with many tasks running in parallel.',
      },
    ],
    certifications: certifications.en,
  },
  skills: {
    eyebrow: 'Skills',
    title: 'Technologies and tools',
    groups: [
      { title: 'Languages', items: ['Java', 'JavaScript', 'HTML', 'CSS'] },
      { title: 'Frontend & UI', items: ['React', 'Vite', 'Flutter', 'UX/UI with Figma'] },
      { title: 'Backend', items: ['Spring', 'REST APIs', 'Microservices', 'Java EE', 'JUnit'] },
      { title: 'Data & AI', items: ['SQL', 'NoSQL', 'Generative AI', 'Prompt engineering', 'AI integration'] },
      { title: 'Tools', items: ['Git', 'GitHub', 'Docker', 'UML'] },
      { title: 'Systems & hardware', items: ['Hardware diagnostics', 'Local networks', 'Operating systems', 'Robotics & 3D printing'] },
      { title: 'Spoken languages', items: ['Italian (native)', 'English B2', 'French & German (basic)'] },
    ],
  },
  project: {
    eyebrow: 'Featured Project',
    title: 'My Tracking App',
    summary: 'My first published personal project: an Android app built with Flutter to keep track of daily consumption, with statistics, goals and data stored on the phone.',
    release: { badge: 'Flutter · Android', label: 'Actively developed, with public versions on GitHub' },
    journey: 'Since the first public version I keep updating it: interface, Android widgets, statistics and data handling, based on everyday use.',
    whyLabel: 'What it taught me',
    whyItMatters: 'Publishing a real app made me decide what to include, how to store the data and how to test every version.',
    proofAria: 'Project proof points',
    proofHighlights: [
      { title: 'Android widgets', text: 'Three sizes (small, medium, large) to log usage straight from the home screen.' },
      { title: 'Statistics and goals', text: 'History by day, week and month, unlockable badges and a reduction plan for each product.' },
      { title: 'CSV backup', text: 'Export and import data as CSV: it always stays under the user’s control.' },
      { title: 'Data on the phone', text: 'No account and no server: all data stays on the device.' },
    ],
    detailsLabel: 'Product details',
    evidence: [
      'Multi-product tracking with a quick selector, archiving and preserved history',
      'Daily count, remaining stock, costs and the last 7 days at a glance',
      'Undo after every entry, periodic reminders and dark / light / system theme',
      'Automated UI tests (golden tests) to keep the design stable from one update to the next',
    ],
    links: { repository: 'Repository', release: 'Latest version' },
    screenshotsAria: 'Project screenshots',
    screenshotsHint: 'Swipe to see more screens',
    screenshots: buildScreenshots('en'),
  },
  contact: {
    eyebrow: 'Contact',
    titleLead: 'Looking for my',
    titleAccent: 'first opportunity',
    titleTrail: 'in software',
    lead: 'Open to internships, jobs and collaborations: write to me, I’m happy to reply.',
    copyEmail: 'Copy email',
    emailCopied: 'Email copied',
    copyFailed: 'Copy failed',
    links: buildContactLinks({ github: 'GitHub', linkedin: 'LinkedIn', cv: 'Download CV' }),
  },
  footer: { closing: 'Designed and built by me.' },
}
