// ===== Testi in italiano =====
import {
  buildContactLinks,
  buildNavItems,
  buildScreenshots,
  certifications,
  sharedProfile,
} from './shared'

export const it = {
  meta: {
    title: 'Lorenzo Caputo — Portfolio',
    description: "Portfolio di Lorenzo Caputo, junior developer in formazione all'ITS Academy Apulia Digital Maker: progetto, percorso e competenze.",
    ogTitle: 'Lorenzo Caputo — Portfolio',
    ogDescription: 'Junior developer in formazione: percorso, competenze e il progetto My Tracking App.',
    twitterTitle: 'Lorenzo Caputo — Portfolio',
    twitterDescription: 'Junior developer in formazione: percorso, competenze e il progetto My Tracking App.',
    ogLocale: 'it_IT',
    image: '/social-preview-it.jpg',
    imageAlt: 'Anteprima del portfolio di Lorenzo Caputo',
  },
  ui: {
    skipToContentLabel: 'Salta al contenuto',
    backToTopAria: 'Torna in alto',
    primaryNavAria: 'Principale',
    mobileNavAria: 'Mobile',
    menuToggleAria: 'Apri o chiudi il menu',
    openGitHubAria: 'Profilo GitHub',
    languageSwitcherAria: 'Seleziona la lingua',
  },
  profile: {
    ...sharedProfile,
    role: 'Junior developer in formazione',
    school: 'ITS Academy Apulia Digital Maker',
    location: 'Lecce, Puglia, Italia',
    portraitAlt: 'Ritratto di Lorenzo Caputo',
    headlineLead: 'Sviluppo software con',
    headlineAccent: 'cura',
    headlineTrail: 'e metodo, un passo alla volta',
    intro: "Sono Lorenzo, junior developer in formazione all'ITS Academy Apulia Digital Maker. Ho portato fino alla pubblicazione My Tracking App, un'app Flutter per Android che continuo a migliorare.",
    introNote: 'Lavoro su frontend, backend Java e hardware: mi piace capire come funziona un progetto per intero.',
    ctaProject: 'Guarda il progetto',
    ctaCv: 'Scarica CV',
  },
  navItems: buildNavItems(['Chi sono', 'Percorso', 'Competenze', 'Progetto', 'Contatti']),
  about: {
    eyebrow: 'Chi sono',
    title: 'Dal lavoro con il pubblico allo sviluppo software',
    lead: "Vengo da anni di lavoro a contatto con il pubblico e da una passione di lunga data per l'hardware: oggi li unisco nel percorso da sviluppatore.",
    paragraphs: [
      "All'ITS Academy studio Java e Spring, OOP, database SQL e NoSQL, Git e architetture cloud. In sala e al front-office ho imparato a gestire la pressione, comunicare con chiarezza e lavorare in squadra.",
      'Nei progetti porto tutte e due: codice ordinato e attenzione a chi lo userà.',
    ],
    principlesEyebrow: 'Come lavoro',
    principles: [
      {
        title: 'Fino in fondo',
        text: 'Porto a termine quello che inizio, dettagli compresi, e lascio il lavoro in ordine per chi viene dopo.',
      },
      {
        title: 'Scelte chiare',
        text: 'Preferisco soluzioni semplici da leggere e da mantenere alle scorciatoie veloci.',
      },
      {
        title: "Visione d'insieme",
        text: 'Prima di mettere mano al codice, cerco di capire come si collegano le parti.',
      },
    ],
  },
  journey: {
    eyebrow: 'Percorso',
    title: 'Formazione ed esperienza',
    educationLabel: 'Formazione',
    experienceLabel: 'Esperienza',
    certificationsLabel: 'Certificazioni',
    education: [
      {
        period: 'gen 2026 – oggi',
        title: 'ITS Academy Apulia Digital Maker',
        place: 'Tecnico Superiore Developer (EQF 5)',
        text: '1.800 ore su Java e Spring (OOP), database SQL e NoSQL, Git/GitHub, architetture cloud e integrazione AI, con laboratori pratici di codifica e debugging.',
      },
      {
        period: '2022',
        title: 'Diploma scientifico-linguistico',
        place: 'I.I.S.S. "G.C. Vanini" – Casarano',
        text: 'Logica, matematica, fisica e lingue straniere; certificazione Cambridge English B2 First.',
      },
    ],
    experience: [
      {
        period: '2014 – oggi',
        title: 'Supporto tecnico e hardware',
        place: 'Freelance',
        text: 'Diagnostica e riparazione di PC e dispositivi mobili, assemblaggio di workstation, configurazione di reti locali e ottimizzazione dei sistemi operativi.',
      },
      {
        period: 'giu – set 2025',
        title: 'Sala e coordinamento del team',
        place: 'Pizzeria Trattoria "Nicolò"',
        text: 'Gestione dei tavoli nei momenti di maggiore affluenza, comande digitali con palmari e coordinamento tra sala e cucina.',
      },
      {
        period: 'lug 2017 – set 2019',
        title: 'Addetto sala e front-office',
        place: 'Ristorante Pizzeria "Il Gambero Rosso"',
        text: 'Accoglienza di clienti stranieri, pagamenti in cassa e servizio bar, con molte attività da gestire in parallelo.',
      },
    ],
    certifications: certifications.it,
  },
  skills: {
    eyebrow: 'Competenze',
    title: 'Tecnologie e strumenti',
    groups: [
      { title: 'Linguaggi', items: ['Java', 'JavaScript', 'HTML', 'CSS'] },
      { title: 'Frontend e UI', items: ['React', 'Vite', 'Flutter', 'UX/UI con Figma'] },
      { title: 'Backend', items: ['Spring', 'REST API', 'Microservizi', 'Java EE', 'JUnit'] },
      { title: 'Dati e AI', items: ['SQL', 'NoSQL', 'AI generativa', 'Prompt engineering', 'Integrazione AI'] },
      { title: 'Strumenti', items: ['Git', 'GitHub', 'Docker', 'UML'] },
      { title: 'Sistemi e hardware', items: ['Diagnostica hardware', 'Reti locali', 'Sistemi operativi', 'Robotica e stampa 3D'] },
      { title: 'Lingue', items: ['Italiano (madrelingua)', 'Inglese B2', 'Francese e tedesco (base)'] },
    ],
  },
  project: {
    eyebrow: 'Progetto in evidenza',
    title: 'My Tracking App',
    summary: "Il mio primo progetto personale pubblicato: un'app Android in Flutter per tenere traccia dei consumi quotidiani, con statistiche, obiettivi e dati salvati sul telefono.",
    release: { badge: 'Flutter · Android', label: 'In sviluppo attivo, con versioni pubbliche su GitHub' },
    journey: "Dalla prima versione pubblica la aggiorno di continuo: interfaccia, widget Android, statistiche e gestione dei dati, in base all'uso quotidiano.",
    whyLabel: 'Cosa mi ha insegnato',
    whyItMatters: "Pubblicare un'app vera mi ha costretto a scegliere cosa includere, come salvare i dati e come verificare ogni versione.",
    proofAria: 'Punti chiave del progetto',
    proofHighlights: [
      { title: 'Widget Android', text: 'Tre dimensioni (piccola, media, grande) per registrare un utilizzo direttamente dalla Home.' },
      { title: 'Statistiche e obiettivi', text: 'Cronologia per giorni, settimane e mesi, badge sbloccabili e un piano di riduzione per ogni prodotto.' },
      { title: 'Backup CSV', text: "Esporta e importa i dati in CSV: restano sempre sotto il controllo dell'utente." },
      { title: 'Dati sul telefono', text: 'Nessun account e nessun server: i dati restano sul dispositivo.' },
    ],
    detailsLabel: 'Dettagli prodotto',
    evidence: [
      'Tracciamento multi-prodotto con selettore rapido, archiviazione e storico conservato',
      'Conteggio giornaliero, scorta residua, costi e andamento degli ultimi 7 giorni',
      'Annulla dopo ogni registrazione, promemoria periodici e tema scuro / chiaro / sistema',
      "Test automatici dell'interfaccia (golden test) per mantenere stabile il design tra un aggiornamento e l'altro",
    ],
    links: { repository: 'Repository', release: 'Ultima versione' },
    screenshotsAria: 'Screenshot del progetto',
    screenshotsHint: 'Scorri per vedere le altre schermate',
    screenshots: buildScreenshots('it'),
  },
  contact: {
    eyebrow: 'Contatti',
    titleLead: 'Cerco la mia',
    titleAccent: 'prima opportunità',
    titleTrail: 'nel software',
    lead: 'Sono aperto a stage, lavoro e collaborazioni: scrivimi, rispondo volentieri.',
    copyEmail: 'Copia email',
    emailCopied: 'Email copiata',
    copyFailed: 'Copia non riuscita',
    links: buildContactLinks({ github: 'GitHub', linkedin: 'LinkedIn', cv: 'Scarica CV' }),
  },
  footer: { closing: 'Progettato e sviluppato da me.' },
}
