// ===== Testi in italiano =====
import {
  buildContactLinks,
  buildNavItems,
  buildScreenshots,
  certifications,
  sharedProfile,
} from './shared'

export const it = {
  meta: {
    title: 'Lorenzo Caputo — Portfolio',
    description: "Portfolio di Lorenzo Caputo, junior developer in formazione all'ITS Academy Apulia Digital Maker: progetto, percorso e competenze.",
    ogTitle: 'Lorenzo Caputo — Portfolio',
    ogDescription: 'Junior developer in formazione: software curato, dall’interfaccia al sistema.',
    twitterTitle: 'Lorenzo Caputo — Portfolio',
    twitterDescription: 'Junior developer in formazione: software curato, dall’interfaccia al sistema.',
    ogLocale: 'it_IT',
    image: '/social-preview-it.jpg',
    imageAlt: 'Anteprima del portfolio di Lorenzo Caputo',
  },
  ui: {
    skipToContentLabel: 'Salta al contenuto',
    backToTopAria: 'Torna in alto',
    primaryNavAria: 'Principale',
    mobileNavAria: 'Mobile',
    menuToggleAria: 'Apri o chiudi il menu',
    openGitHubAria: 'Profilo GitHub',
    languageSwitcherAria: 'Seleziona la lingua',
  },
  profile: {
    ...sharedProfile,
    role: 'Junior Developer in Formazione',
    school: 'ITS Academy Apulia Digital Maker',
    location: 'Lecce, Puglia, Italia',
    portraitAlt: 'Ritratto di Lorenzo Caputo',
    headlineLead: 'Costruisco software con',
    headlineAccent: 'cura',
    headlineTrail: "e metodo, dall'interfaccia al sistema.",
    intro: "Sono Lorenzo, junior developer in formazione all'ITS Academy Apulia Digital Maker. Ho portato fino alla pubblicazione My Tracking App, un'app Flutter per Android che continuo a migliorare.",
    introNote: 'Mi muovo tra frontend, backend Java e hardware: voglio capire come funziona tutto il sistema, non solo lo schermo.',
    ctaProject: 'Guarda il progetto',
    ctaCv: 'Scarica CV',
  },
  navItems: buildNavItems(['Chi sono', 'Percorso', 'Competenze', 'Progetto', 'Contatti']),
  about: {
    eyebrow: 'Chi sono',
    title: 'Dal lavoro con il pubblico allo sviluppo software.',
    lead: "Vengo da anni di lavoro a contatto con il pubblico e da una passione di lunga data per l'hardware: oggi li unisco nel percorso da sviluppatore.",
    paragraphs: [
      "All'ITS Academy studio Java, OOP, database SQL, Git e architetture cloud. In sala e al front-office ho imparato a gestire la pressione, comunicare con chiarezza e lavorare in squadra.",
      'Nei progetti porto entrambe le cose: codice curato e attenzione a chi lo userà.',
    ],
    principlesEyebrow: 'Come lavoro',
    principles: [
      {
        title: 'Fino in fondo',
        text: 'Finisco quello che inizio, dettagli compresi, e lascio il lavoro in uno stato su cui altri possono contare.',
      },
      {
        title: 'Scelte chiare',
        text: 'Preferisco soluzioni leggibili e compromessi dichiarati a scorciatoie difficili da mantenere.',
      },
      {
        title: "Visione d'insieme",
        text: "Dall'interfaccia al dispositivo, cerco di capire tutto il sistema prima di intervenire.",
      },
    ],
  },
  journey: {
    eyebrow: 'Percorso',
    title: 'Formazione ed esperienza.',
    educationLabel: 'Formazione',
    experienceLabel: 'Esperienza',
    certificationsLabel: 'Certificazioni',
    education: [
      {
        period: 'gen 2026 – oggi',
        title: 'ITS Academy Apulia Digital Maker',
        place: 'Tecnico Superiore Developer (EQF 5)',
        text: '1.800 ore su Java e C# (OOP), database SQL, Git/GitHub, architetture cloud e integrazione AI, con laboratori pratici di codifica e debugging.',
      },
      {
        period: '2022',
        title: 'Diploma scientifico-linguistico',
        place: 'I.I.S.S. "G.C. Vanini" – Casarano',
        text: 'Logica, matematica, fisica e lingue straniere; certificazione Cambridge English B2 First.',
      },
    ],
    experience: [
      {
        period: '2014 – oggi',
        title: 'Supporto tecnico e hardware',
        place: 'Freelance',
        text: 'Diagnostica e riparazione di PC e dispositivi mobili, assemblaggio di workstation, configurazione di reti locali e ottimizzazione dei sistemi operativi.',
      },
      {
        period: 'giu – set 2025',
        title: 'Sala e coordinamento del team',
        place: 'Pizzeria Trattoria "Nicolò"',
        text: 'Gestione del rango nei momenti di pieno carico, comande digitali con palmari e coordinamento tra sala e cucina.',
      },
      {
        period: 'lug 2017 – set 2019',
        title: 'Addetto sala e front-office',
        place: 'Ristorante Pizzeria "Il Gambero Rosso"',
        text: 'Accoglienza di clienti stranieri, pagamenti e front-desk, con molte attività da gestire in parallelo.',
      },
    ],
    certifications: certifications.it,
  },
  skills: {
    eyebrow: 'Competenze',
    title: 'Tecnologie e strumenti.',
    groups: [
      { title: 'Linguaggi', items: ['Java', 'JavaScript', 'HTML', 'CSS'] },
      { title: 'Frontend e UI', items: ['React', 'Vite', 'Flutter', 'UX/UI con Figma'] },
      { title: 'Backend', items: ['Spring', 'REST API', 'Microservizi', 'Java EE', 'JUnit'] },
      { title: 'Dati e AI', items: ['SQL', 'NoSQL', 'AI generativa', 'Prompt engineering', 'Integrazione AI'] },
      { title: 'Strumenti', items: ['Git', 'GitHub', 'Docker', 'UML'] },
      { title: 'Sistemi e hardware', items: ['Diagnostica hardware', 'Reti locali', 'Sistemi operativi', 'Robotica e stampa 3D'] },
      { title: 'Lingue', items: ['Italiano (madrelingua)', 'Inglese B2', 'Francese e tedesco (base)'] },
    ],
  },
  project: {
    eyebrow: 'Progetto in evidenza',
    title: 'My Tracking App',
    summary: "Il mio primo progetto personale portato fino alla release: un'app Flutter per tracciare l'uso ricorrente di prodotti, con interfaccia pulita e dati gestiti in locale.",
    release: { badge: 'Flutter · Android', label: 'In sviluppo attivo, con release pubbliche su GitHub' },
    journey: "Dalla prima release pubblica a oggi: aggiornamenti continui su interfaccia, widget Android, statistiche e gestione dei dati, guidati dall'uso reale.",
    whyLabel: 'Perché conta',
    whyItMatters: 'Va oltre una demo: mi ha costretto a prendere decisioni reali su scope, gestione dei dati e qualità della release.',
    proofAria: 'Punti chiave del progetto',
    proofHighlights: [
      { title: 'Widget Android', text: 'Tre layout (small, medium, large) per registrare un utilizzo direttamente dalla Home.' },
      { title: 'Statistiche e obiettivi', text: 'Cronologia per giorni, settimane e mesi, badge sbloccabili e un piano di riduzione per ogni prodotto.' },
      { title: 'Backup CSV', text: "Backup ed export in CSV: i dati restano portabili e sotto il controllo dell'utente." },
      { title: 'Local-first', text: 'Nessun account, nessun backend — i dati restano sul dispositivo.' },
    ],
    detailsLabel: 'Dettagli prodotto',
    evidence: [
      'Tracciamento multi-prodotto con selettore rapido, archiviazione e storico conservato',
      'Conteggio giornaliero, scorta residua, costi e andamento degli ultimi 7 giorni',
      'Annulla dopo ogni registrazione, promemoria periodici e tema scuro / chiaro / sistema',
      "Test automatici dell'interfaccia (golden test) per mantenere stabile il design tra un aggiornamento e l'altro",
    ],
    links: { repository: 'Repository', release: 'Ultima release' },
    screenshotsAria: 'Screenshot del progetto',
    screenshotsHint: 'Scorri per vedere le altre schermate',
    screenshots: buildScreenshots('it'),
  },
  contact: {
    eyebrow: 'Contatti',
    titleLead: 'Pronto per un',
    titleAccent: 'passo serio',
    titleTrail: 'nel software.',
    lead: 'Aperto a opportunità, collaborazioni e confronti: scrivimi, rispondo volentieri.',
    copyEmail: 'Copia email',
    emailCopied: 'Email copiata',
    copyFailed: 'Copia non riuscita',
    links: buildContactLinks({ github: 'GitHub', linkedin: 'LinkedIn', cv: 'Scarica CV' }),
  },
  footer: { closing: 'Costruito con cura. Altro in arrivo.' },
}
